config/routes.rb
Rails.application.routes.draw do

  get 'relationship/create'

  get 'relationship/destroy'

  root 'sessions#new'

  get 'login' => 'sessions#new'

  post 'login'   => 'sessions#create'

  get 'signup' => 'users#new'

  get 'logout' => 'sessions#destroy'

  get '/user/:id/followers' => 'users#followers'

  resources :users
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title , presence: true , length: { minimum: 5, maximum: 20 }
  validates :body , presence: true, length: { minimum: 25, maximum: 120 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :follower , class_name: "User"
  belongs_to :followed , class_name: "User"

  validates :follower_id, :presence => true
  validates :followed_id, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts , dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id", class_name:  "Relationship", dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  before_save { self.email = email.downcase }



  # Validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name , presence: true , length: {minimum: 6}
  validates :email , presence: true , length: {minimum: 6}, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  def follow(other_user)
    self.followed_users.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    self.followed_users.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    followed_users.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
    private
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :logged_in_user , only: [:create,:destroy]

  def new
    @post = Post.new
  end

  def create
    @post = @current_user.posts.build(post_params)
    if !@post.save
      flash[:notice] = "SUCCESS"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete
  end


  private
  def post_params
    params.require(:post).permit(:body,:title,:user_id)
  end



end

app/controllers/relationship_controller.rb
class RelationshipController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login(user)
      redirect_to posts_path
    else
      flash[:notice] = "Invalid Username or Password"
      flash[:color]= "invalid"
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Awesome!"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
    else
      render 'edit'
    end
  end

  def destroy
    @user.delete
  end


  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:confirm_password,:username)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<%= link_to("Logout",logout_path)%>

<h2>Post Feed</h2>
<%@posts.all.each do |post|%>
<%= post.title%><br/>
<%= post.body%><br/>
<% user = User.find(post.user_id) rescue nil %>
Posted by<%=link_to "#{user.name}", user_path(id: user.id)%>
<% end %>
<h3>
  <%=link_to("Add a post",new_post_path)%>
</h3>

app/views/posts/new.html.erb
<%if @post.errors.any?%>
<%@post.errors.full_messages.each do |msg| %>
<%= msg %>
<%end%>
<%end%>


<% provide(:title, "Add a post") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %><br/><br/>

      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control' %>

      <%= f.submit "Create Post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h3><%= @post.title %></h3>
<%= @post.body %>
<% user = User.find(@post.user_id)%>
Posted by <%= link_to "#{user.name}", user_path(id: user.id)%>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/relationship/create.html.erb
<h1>Relationship#create</h1>
<p>Find me in app/views/relationship/create.html.erb</p>

app/views/relationship/destroy.html.erb
<h1>Relationship#destroy</h1>
<p>Find me in app/views/relationship/destroy.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<%@users.each do |user|%>

app/views/users/new.html.erb
<%if @user.errors.any?%>
<%@user.errors.full_messages.each do |msg| %>
<%= msg %>
<%end%>
<%end%>


<% provide(:title, "Signup") %>
<h1>Signup</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Sign up", class: "btn btn-primary" %>
    <% end %>

    <p>Signup <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1><br/>
<%= @user.email %><br/>
<h2><%= @user.name%>'s Posts</h2>
Followers <%= @user.followers.count %><br/>
Following <%= @user.following.count %><br/>
<%= @user.posts.each do |post| %>
<%= link_to "#{post.title}", post_path(id: post.id)%>
<%end%>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>